### PR TITLE
Add John's projects

### PR DESCRIPTION
**Pull request by JohnPettigrew**
These commits do two things: add my content to the showcase; and add styles and fonts for figure captions. I've added the lighter font because the bold is a bit much for captions IMO.

### CODE REVIEW

**Review by EmmaB — APPROVED** [review]
Superb, thank you!

**Comment by JohnPettigrew** [comment]
Thanks, Emma. Should I add the 400 weight to the other pages, in case someone tries to use the figcaption styles elsewhere?

**Comment by EmmaB** [comment]
No, I don't think so. It'll be a fun learning opportunity to track down, if someone goes that route!

**Comment by JohnPettigrew** [comment]
👍😀

**Comment by EmmaB** [comment]
Hi @JohnPettigrew -- the code in this PR you kindly wrote last year, despite it showing as merged, is not in `main` and not on the website as a result. I am very sorry about this! It might have been because last year we renamed the default `master` branch to `main`, and this PR got merged into a non-existent branch. My great apologies anyway and I'll get it resolved.

**Pull request merged**
